<a href="https://colab.research.google.com/github/dixondanty/AI-ML-internship/blob/main/day4/numpyp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
type(arr)


numpy.ndarray

In [ ]:
arr.shape

(3,)

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print("Addition:", arr1 + arr2)

# Multiplication
print("Multiplication:", arr1 * arr2)


Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [4]:
arr = np.arange(1, 10)

new_arr = arr.reshape(3, 3)

print(new_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Create a two-dimensional array
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [ ]:
arr2.shape

(2, 2)

In [ ]:
# Create a three-dimensional array
threeD_array = np.array([[[1,2],[3,4]],
                        [[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [ ]:
py_list = [1, 2, 3]
print(py_list*2)


[1, 2, 3, 1, 2, 3]


In [ ]:
# NumPy array
np_array = np.array([1, 2, 3])
print(np_array*2)

[2 4 6]
